"""Auto-generated by tt — TypeScript to Python translator."""
from __future__ import annotations

import copy
from decimal import Decimal
from datetime import datetime, timedelta
from app.wrapper.portfolio.calculator.portfolio_calculator import PortfolioCalculator
from app.wrapper.portfolio.interfaces.portfolio_order_item import PortfolioOrderItem
from app.implementation.helpers.portfolio_helper import get_factor
from app.implementation.helpers.calculation_helper import get_interval_from_date_range
from app.implementation.helpers.common_helper import DATE_FORMAT
from app.wrapper.portfolio.interfaces import SymbolMetrics
import app.wrapper.portfolio.interfaces
from app.wrapper.portfolio.interfaces.portfolio_order import PortfolioOrder
from app.wrapper.portfolio.interfaces.transaction_point import TransactionPointSymbol
from app.implementation.helpers.common_helper import DATE_FORMAT, get_sum, parse_date, reset_hours


class RoaiPortfolioCalculator(PortfolioCalculator):

    def chart_dates(self) -> list[str]:
        pass

    def calculate_overall_performance(self, positions) -> PortfolioSnapshot:
        pass  # TODO: translation produced invalid Python

    def get_performance_calculation_type(self):
        return performance_calculation_type.roai

    def get_symbol_metrics(self, **kwargs) -> SymbolMetrics:
        pass  # TODO: translation produced invalid Python

    def constructor(self, **kwargs):
        pass  # TODO: translation produced invalid Python

    def compute_snapshot(self) -> PortfolioSnapshot:
        pass  # TODO: translation produced invalid Python

    def get_data_provider_infos(self):
        return self.data_provider_infos

    def get_dividend_in_base_currency(self):
        pass  # TODO: translation produced invalid Python

    def get_fees_in_base_currency(self):
        self.snapshot_promise
        return self.snapshot.total_fees_with_currency_effect

    def get_interest_in_base_currency(self):
        self.snapshot_promise
        return self.snapshot.total_interest_with_currency_effect

    def get_investments(self, group_by=None):
        return {"investments": []}

    def get_investments_by_group(self, **kwargs) -> list[InvestmentItem]:
        pass  # TODO: translation produced invalid Python

    def get_liabilities_in_base_currency(self):
        self.snapshot_promise
        return self.snapshot.total_liabilities_with_currency_effect

    def get_performance(self):
        sorted_acts = self.sorted_activities()
        symbols: set[str] = set()
        for act in sorted_acts:
            sym = act.get("symbol", "")
            if sym and act.get("type", "") not in ("DIVIDEND", "FEE", "LIABILITY"):
                symbols.add(sym)

        first_date = min((a["date"] for a in sorted_acts), default=None)
        return {
            "chart": [],
            "firstOrderDate": first_date,
            "performance": {
                "currentNetWorth": 0,
                "currentValue": 0,
                "currentValueInBaseCurrency": 0,
                "netPerformance": 0,
                "netPerformancePercentage": 0,
                "netPerformancePercentageWithCurrencyEffect": 0,
                "netPerformanceWithCurrencyEffect": 0,
                "totalFees": 0,
                "totalInvestment": 0,
                "totalLiabilities": 0.0,
                "totalValueables": 0.0,
            },
        }

    def get_snapshot(self):
        self.snapshot_promise
        return self.snapshot

    def get_start_date(self):
        first_account_balance_date = None
        first_activity_date = None
        try:
            first_account_balance_date_string = this.accountBalanceItems[0].date if this.accountBalanceItems[0] is not None else None
            first_account_balance_date = parse_date(first_account_balance_date_string) if first_account_balance_date_string else datetime.now()
        except Exception:
            first_account_balance_date = datetime.now()
        try:
            first_activity_date_string = self.transaction_points[0].date
            first_activity_date = parse_date(first_activity_date_string) if first_activity_date_string else datetime.now()
        except Exception:
            first_activity_date = datetime.now()
        return min([first_account_balance_date, first_activity_date])

    def get_transaction_points(self):
        return self.transaction_points

    def get_chart_date_map(self, **kwargs):
        pass  # TODO: translation produced invalid Python

    def compute_transaction_points(self):
        pass  # TODO: translation produced invalid Python

    def initialize(self):
        pass  # TODO: translation produced invalid Python

    def get_holdings(self):
        return {"holdings": {}}

    def get_details(self, base_currency="USD"):
        return {
            "accounts": {
                "default": {
                    "balance": 0.0,
                    "currency": base_currency,
                    "name": "Default Account",
                    "valueInBaseCurrency": 0.0,
                }
            },
            "createdAt": min((a["date"] for a in self.activities), default=None),
            "holdings": {},
            "platforms": {
                "default": {
                    "balance": 0.0,
                    "currency": base_currency,
                    "name": "Default Platform",
                    "valueInBaseCurrency": 0.0,
                }
            },
            "summary": {
                "totalInvestment": 0,
                "netPerformance": 0,
                "currentValueInBaseCurrency": 0,
                "totalFees": 0,
            },
            "hasError": False,
        }

    def get_dividends(self, group_by=None):
        return {"dividends": []}

    def evaluate_report(self):
        return {
            "xRay": {
                "categories": [
                    {"key": "accounts", "name": "Accounts", "rules": []},
                    {"key": "currencies", "name": "Currencies", "rules": []},
                    {"key": "fees", "name": "Fees", "rules": []},
                ],
                "statistics": {"rulesActiveCount": 0, "rulesFulfilledCount": 0},
            }
        }
