#!/usr/bin/env bash
# Start the tt-translated Python Ghostfolio project (translations/ghostfolio_pytx),
# run the integration test suite against it, then stop the server.
#
# translations/ghostfolio_pytx is generated by running: uv run --project tt tt translate
#
# Usage:
#   bash projecttests/tools/spinup_and_test_ghostfolio_pytx.sh [pytest-args...]
#
# Options (env vars):
#   PYTX_PORT              Host port to bind (default: 3335)
#   KEEP_UP                Set to 1 to leave the server running after tests
#   RUN_IN_PYTHON_DOCKER   Set to 1 to run Python commands inside a Docker container
#   PYTHON_DOCKER_IMAGE    Docker image to use (default: ghcr.io/astral-sh/uv:python3.12-bookworm-slim)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTX_DIR="$ROOT_DIR/translations/ghostfolio_pytx"
PORT="${PYTX_PORT:-3335}"
API_URL="http://localhost:$PORT"
PYTHON_DOCKER_IMAGE="${PYTHON_DOCKER_IMAGE:-ghcr.io/astral-sh/uv:python3.12-bookworm-slim}"
# Unique container name per invocation to allow parallel runs
DOCKER_CONTAINER="ghostfolio-pytx-$$"

# ===========================================================================
# Docker mode: run uv commands inside a Python Docker container
# ===========================================================================
if [ "${RUN_IN_PYTHON_DOCKER:-0}" = "1" ]; then
  echo "=== Docker mode (RUN_IN_PYTHON_DOCKER=1, image: $PYTHON_DOCKER_IMAGE) ==="

  if ! command -v docker &>/dev/null; then
    echo "ERROR: 'docker' not found. Install Docker to use RUN_IN_PYTHON_DOCKER=1." >&2
    exit 1
  fi

  stop_server() {
    docker stop "$DOCKER_CONTAINER" 2>/dev/null || true
  }
  trap stop_server EXIT

  # -------------------------------------------------------------------------
  # Start FastAPI server inside Docker, port-mapped to the host
  # -------------------------------------------------------------------------
  echo "Starting tt-translated ghostfolio_pytx in Docker (port $PORT)..."
  docker run -d --rm \
    --name "$DOCKER_CONTAINER" \
    -p "${PORT}:${PORT}" \
    -v "$ROOT_DIR:/repo" \
    -w "/repo/translations/ghostfolio_pytx" \
    "$PYTHON_DOCKER_IMAGE" \
    uv run python -m uvicorn app.main:app \
      --host 0.0.0.0 \
      --port "$PORT" \
      --log-level warning

  # -------------------------------------------------------------------------
  # Wait for the server to be ready
  # -------------------------------------------------------------------------
  echo "Waiting for API to be ready..."
  for i in $(seq 1 30); do
    if curl -sf "$API_URL/api/v1/health" > /dev/null 2>&1; then
      echo "API is up."
      break
    fi
    if [ "$i" -eq 30 ]; then
      echo "ERROR: API did not become healthy after 30 s" >&2
      exit 1
    fi
    sleep 1
  done

  # -------------------------------------------------------------------------
  # Run tests inside Docker; reach the server via host.docker.internal
  # --add-host works on Linux (Docker 20.10+) and Docker Desktop on macOS
  # UV_LINK_MODE=copy avoids hardlink warnings when cache is on a different fs
  # Sync dev extras first so pytest is available, then run the suite
  # -------------------------------------------------------------------------
  EXIT_CODE=0
  docker run --rm \
    --add-host "host.docker.internal:host-gateway" \
    -e "GHOSTFOLIO_API_URL=http://host.docker.internal:${PORT}" \
    -e "UV_LINK_MODE=copy" \
    -v "$ROOT_DIR:/repo" \
    -w /repo \
    "$PYTHON_DOCKER_IMAGE" \
    sh -c "uv sync --project tt --extra dev --quiet && uv run --project tt pytest projecttests/ghostfolio_api -v" \
    || EXIT_CODE=$?

  if [ "${KEEP_UP:-0}" != "1" ]; then
    echo "Stopping ghostfolio_pytx Docker container..."
    stop_server
  fi

  exit $EXIT_CODE
fi

# ===========================================================================
# Non-Docker mode (default)
# ===========================================================================

# ---------------------------------------------------------------------------
# Resolve uv
# ---------------------------------------------------------------------------
UV="uv"
if ! command -v uv &>/dev/null; then
  echo "ERROR: 'uv' not found. Install it from https://github.com/astral-sh/uv" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Sync Python deps for the skeleton project
# ---------------------------------------------------------------------------
"$UV" sync --project "$PYTX_DIR" --extra dev --quiet

# ---------------------------------------------------------------------------
# Start the FastAPI skeleton in the background
# ---------------------------------------------------------------------------
echo "Starting tt-translated ghostfolio_pytx (port $PORT)..."
(cd "$PYTX_DIR" && "$UV" run python -m uvicorn app.main:app \
  --host 127.0.0.1 \
  --port "$PORT" \
  --log-level warning) \
  &
SERVER_PID=$!

stop_server() {
  if kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
  fi
  # Also kill any other process that may have grabbed the port
  PIDS="$(lsof -ti:"$PORT" 2>/dev/null)"
  if [ -n "$PIDS" ]; then
    echo "$PIDS" | xargs kill 2>/dev/null || true
  fi
}
trap stop_server EXIT

# ---------------------------------------------------------------------------
# Wait for the server to be ready
# ---------------------------------------------------------------------------
echo "Waiting for API to be ready..."
for i in $(seq 1 30); do
  if curl -sf "$API_URL/api/v1/health" > /dev/null 2>&1; then
    echo "API is up."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "ERROR: API did not become healthy after 30 s" >&2
    exit 1
  fi
  sleep 1
done

# ---------------------------------------------------------------------------
# Run the tests (same suite, different API URL)
# ---------------------------------------------------------------------------
EXIT_CODE=0
GHOSTFOLIO_API_URL="$API_URL" \
  "$UV" run --project "$ROOT_DIR/tt" pytest "$ROOT_DIR/projecttests/ghostfolio_api" -v "$@" \
  || EXIT_CODE=$?

# ---------------------------------------------------------------------------
# Tear down
# ---------------------------------------------------------------------------
if [ "${KEEP_UP:-0}" != "1" ]; then
  echo "Stopping ghostfolio_pytx server..."
  stop_server
fi

exit $EXIT_CODE
