#!/usr/bin/env bash
# Start the tt-translated Python Arquero project (translations/arquero_pytx),
# run the integration test suite against it, then stop the server.
#
# translations/arquero_pytx is generated by running:
#   uv run --project tt tt translate \
#       --source-dir projects/arquero/src \
#       --output translations/arquero_pytx
#
# Usage:
#   bash projecttests/tools/spinup_and_test_arquero_pytx.sh [pytest-args...]
#
# Options (env vars):
#   ARQUERO_PYTX_PORT   Host port to bind (default: 3338)
#   KEEP_UP             Set to 1 to leave the server running after tests
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTX_DIR="$ROOT_DIR/translations/arquero_pytx"
PORT="${ARQUERO_PYTX_PORT:-3338}"
API_URL="http://localhost:$PORT"

# ---------------------------------------------------------------------------
# Resolve uv
# ---------------------------------------------------------------------------
UV="uv"
if ! command -v uv &>/dev/null; then
  echo "ERROR: 'uv' not found. Install it from https://github.com/astral-sh/uv" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Sync Python deps for the translated project
# ---------------------------------------------------------------------------
"$UV" sync --project "$PYTX_DIR" --extra dev --quiet

# ---------------------------------------------------------------------------
# Start the FastAPI server in the background
# ---------------------------------------------------------------------------
echo "Starting tt-translated arquero_pytx (port $PORT)..."
(cd "$PYTX_DIR" && "$UV" run python -m uvicorn app.main:app \
  --host 127.0.0.1 \
  --port "$PORT" \
  --log-level warning) \
  &
SERVER_PID=$!

stop_server() {
  if kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
  fi
  PIDS="$(lsof -ti:"$PORT" 2>/dev/null)"
  if [ -n "$PIDS" ]; then
    echo "$PIDS" | xargs kill 2>/dev/null || true
  fi
}
trap stop_server EXIT

# ---------------------------------------------------------------------------
# Wait for the server to be ready
# ---------------------------------------------------------------------------
echo "Waiting for API to be ready..."
for i in $(seq 1 30); do
  if curl -sf "$API_URL/health" > /dev/null 2>&1; then
    echo "API is up."
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "ERROR: API did not become healthy after 30 s" >&2
    exit 1
  fi
  sleep 1
done

# ---------------------------------------------------------------------------
# Run the tests
# ---------------------------------------------------------------------------
EXIT_CODE=0
ARQUERO_API_URL="$API_URL" \
  "$UV" run --project "$ROOT_DIR/tt" pytest "$ROOT_DIR/projecttests/arquero_api" -v "$@" \
  || EXIT_CODE=$?

# ---------------------------------------------------------------------------
# Tear down
# ---------------------------------------------------------------------------
if [ "${KEEP_UP:-0}" != "1" ]; then
  echo "Stopping arquero_pytx server..."
  stop_server
fi

exit $EXIT_CODE
