# Generated by tt translator
"""Generic helper utilities for translated code.

Provides date handling and decimal convenience functions.
These are structural helpers, not domain-specific logic.
"""

from __future__ import annotations

from datetime import date, timedelta
from decimal import Decimal


D = Decimal


def parse_date(s: str) -> date:
    """Parse YYYY-MM-DD string to date."""
    return date.fromisoformat(s)


def date_str(d: date) -> str:
    """Format date as YYYY-MM-DD string."""
    return d.isoformat()


def each_year_of_interval(start: date, end: date) -> list[date]:
    """Return Jan 1 of each year in the range [start, end]."""
    return [date(y, 1, 1) for y in range(start.year, end.year + 1)]


def difference_in_days(a: date, b: date) -> int:
    """Number of days between two dates."""
    return (a - b).days
