"""
Python source code generator.

Takes the output of the transformer (Python source strings for methods/classes)
and assembles a complete Python source file with proper indentation and imports.
"""
from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_method(method_info: dict, indent: int = 1) -> str:
    """Generate a Python method definition string.

    Args:
        method_info: Dict with keys:
            - ``name`` (str): Method name (snake_case).
            - ``params`` (list[str]): Parameter names (without ``self``).
            - ``return_type`` (str | None): Python return type annotation.
            - ``body_lines`` (str): Pre-translated body source (multi-line string).
        indent: Indentation level for the ``def`` line (1 = inside a class).

    Returns:
        A Python method definition string, properly indented.
    """
    pad = "    " * indent
    inner_pad = "    " * (indent + 1)

    name = method_info["name"]
    params = method_info.get("params", [])
    return_type = method_info.get("return_type")
    body_lines: str = method_info.get("body_lines", "")

    # Build parameter list — always prepend self
    all_params = ["self"] + list(params)
    params_str = ", ".join(all_params)

    # Return type annotation
    ret_ann = f" -> {return_type}" if return_type else ""

    sig = f"{pad}def {name}({params_str}){ret_ann}:"

    # Body: re-indent each line to indent+1 level
    if body_lines and body_lines.strip():
        body_text = _reindent(body_lines, indent + 1)
        return f"{sig}\n{body_text}"
    else:
        return f"{sig}\n{inner_pad}pass"


def generate_class(class_info: dict) -> str:
    """Generate a Python class definition string.

    Args:
        class_info: Dict with keys:
            - ``name`` (str): Class name.
            - ``base_class`` (str | None): Base class name, or None.
            - ``methods`` (list[dict]): List of method_info dicts (see generate_method).

    Returns:
        A Python class definition string.
    """
    name = class_info["name"]
    base_class = class_info.get("base_class")
    methods = class_info.get("methods", [])

    inheritance = f"({base_class})" if base_class else ""
    lines = [f"class {name}{inheritance}:"]

    if not methods:
        lines.append("    pass")
        return "\n".join(lines)

    for method_info in methods:
        method_src = generate_method(method_info, indent=1)
        lines.append("")
        lines.append(method_src)

    return "\n".join(lines)


def generate_module(imports: list[str], classes: list[dict]) -> str:
    """Generate a complete Python module source string.

    Args:
        imports: List of Python import statement strings (e.g. ``"from decimal import Decimal"``).
        classes: List of class_info dicts (see generate_class).

    Returns:
        A complete Python module source string.
    """
    parts: list[str] = ['"""Auto-generated by tt — TypeScript to Python translator."""']
    parts.append("from __future__ import annotations")
    parts.append("")

    # Deduplicate and emit imports
    seen: set[str] = set()
    for imp in imports:
        if imp and not imp.startswith("#") and imp not in seen:
            parts.append(imp)
            seen.add(imp)

    parts.append("")
    parts.append("")

    for class_info in classes:
        parts.append(generate_class(class_info))
        parts.append("")

    return "\n".join(parts)


def write_init_files(output_dir: Path) -> None:
    """Create ``__init__.py`` in all directories under output_dir that contain .py files.

    Args:
        output_dir: Root directory to walk. All subdirectories containing ``.py``
            files will receive an ``__init__.py`` if one does not already exist.
    """
    for py_file in output_dir.rglob("*.py"):
        init = py_file.parent / "__init__.py"
        if not init.exists():
            init.write_text("", encoding="utf-8")
            logger.debug("Created %s", init)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _reindent(text: str, target_indent: int) -> str:
    """Re-indent a block of source text to the given indent level.

    Strips the common leading whitespace from all non-empty lines, then
    re-applies ``target_indent * 4`` spaces.

    Args:
        text: Multi-line source string.
        target_indent: Number of 4-space indent levels to apply.

    Returns:
        Re-indented source string.
    """
    lines = text.splitlines()
    if not lines:
        return "    " * target_indent + "pass"

    # Find minimum indentation of non-empty lines
    non_empty = [ln for ln in lines if ln.strip()]
    if not non_empty:
        return "    " * target_indent + "pass"

    min_indent = min(len(ln) - len(ln.lstrip()) for ln in non_empty)
    pad = "    " * target_indent

    result_lines: list[str] = []
    for ln in lines:
        if ln.strip():
            result_lines.append(pad + ln[min_indent:])
        else:
            result_lines.append("")

    return "\n".join(result_lines)
